# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Boilercoding
email: boilercoding@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site covers all kinds of topics related to software development with Ruby on Rails.



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://boilercoding.com" # the base hostname & protocol for your site

#sidebar
default-image: logo-big.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.


# Build settings
markdown: kramdown
permalink: /:title/

# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: boilercoding

#social
facebook: http://facebook.com/Boilercoding-373035779735116
twitter: http://twitter.com/@boilercoding
github: http://github.com/boilercoding

#facebook like box
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/boilercoding/
fb-page-title: boilercoding

# Sass style
sass:
  style: compressed

# Ruby Gems
gems:
  - jekyll-seo-tag