# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Boilercoding
email: boilercoding@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full Stack Web Application Development



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elixirprogrammer.com" # the base hostname & protocol for your site

#sidebar
default-image: logo-big.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.


# Build settings
markdown: kramdown
permalink: /blog/:title/

# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: boilercoding

#social
instagram: https://www.instagram.com/elixirprogrammer
twitter: https://twitter.com/elixirprogrammr
github: https://github.com/elixirprogrammer

# Sass style
sass:
  style: compressed

# Ruby Gems
gems:
  - jekyll-seo-tag